name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA2HPG322B3GXOH5VC
          aws-secret-access-key: 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
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan
          echo "TF_PLAN=$(base64 tfplan)" >> $GITHUB_ENV

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo $TF_PLAN | base64 --decode > tfplan
          terraform apply tfplan

      - name: Terraform Apply
        run: terraform
